# Generated by Django 6.0.3 on 2026-03-08 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('localizacao_texto', models.CharField(max_length=255)),
                ('data_ocorrencia', models.DateField()),
                ('resolvido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='coletas/%Y/%m/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriaresiduo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
