# Generated by Django 6.0.3 on 2026-03-08 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pontocoleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='data_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='localizacao_texto',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='resolvido',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='denuncias/'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
