# Generated by Django 6.0.3 on 2026-03-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_denuncia_data_ocorrencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaresiduo',
            name='icone',
        ),
        migrations.AddField(
            model_name='categoriaresiduo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='latitude',
            field=models.FloatField(default=-26.3725),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='longitude',
            field=models.FloatField(default=-7258),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='solicitacoes/'),
        ),
    ]
