# Generated by Django 6.0.3 on 2026-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_categoriaresiduo_icone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='latitude',
            field=models.FloatField(default=-26.3725),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='longitude',
            field=models.FloatField(default=-48.721),
        ),
        migrations.AlterField(
            model_name='pontocoleta',
            name='latitude',
            field=models.FloatField(default=-26.3725),
        ),
        migrations.AlterField(
            model_name='pontocoleta',
            name='longitude',
            field=models.FloatField(default=-48.721),
        ),
    ]
