# Generated by Django 6.0.3 on 2026-03-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_denuncia_latitude_alter_denuncia_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontocoleta',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='solicitacaocoleta',
            name='endereco',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaocoleta',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitacaocoleta',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaocoleta',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo_problema',
            field=models.CharField(choices=[('ELETRONICOS', 'Eletrônicos (TV, Baterias, etc)'), ('VOLUMOSOS', 'Móveis Volumosos (Sofá, Armários)'), ('RECICLAVEIS', 'Papel, Plástico, Vidro e Metal'), ('OLEO', 'Óleo de Cozinha Usado'), ('PODA', 'Restos de Poda / Jardim')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pontocoleta',
            name='tipo_residuo',
            field=models.CharField(choices=[('ELETRONICOS', 'Eletrônicos (TV, Baterias, etc)'), ('VOLUMOSOS', 'Móveis Volumosos (Sofá, Armários)'), ('RECICLAVEIS', 'Papel, Plástico, Vidro e Metal'), ('OLEO', 'Óleo de Cozinha Usado'), ('PODA', 'Restos de Poda / Jardim')], max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='categoria',
            field=models.CharField(choices=[('ELETRONICOS', 'Eletrônicos (TV, Baterias, etc)'), ('VOLUMOSOS', 'Móveis Volumosos (Sofá, Armários)'), ('RECICLAVEIS', 'Papel, Plástico, Vidro e Metal'), ('OLEO', 'Óleo de Cozinha Usado'), ('PODA', 'Restos de Poda / Jardim')], max_length=100),
        ),
    ]
