# Generated by Django 6.0.3 on 2026-03-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pontocoleta_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocoleta',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='endereco_numero',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='rua',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
