# Generated by Django 6.0.3 on 2026-03-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solicitacaocoleta_cep_alter_solicitacaocoleta_bairro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Denuncia',
        ),
    ]
